name: Auto Grade

on:
  push:
  workflow_dispatch:
    inputs:
      due_date:
        description: "Override ISO due date/time (default is 2025-10-08T23:59:59+03:00)"
        required: false
        default: ""

jobs:
  grade:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Use Node with cache if lockfiles exist
      - name: Use Node (cache)
        if: ${{ hashFiles('5-4-react-rendering-lists/package-lock.json', '5-4-react-rendering-lists/npm-shrinkwrap.json', '5-4-react-rendering-lists/yarn.lock') != '' }}
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: npm
          cache-dependency-path: |
            5-4-react-rendering-lists/package-lock.json
            5-4-react-rendering-lists/npm-shrinkwrap.json
            5-4-react-rendering-lists/yarn.lock

      # Fallback if no lockfile found
      - name: Use Node (no cache)
        if: ${{ hashFiles('5-4-react-rendering-lists/package-lock.json', '5-4-react-rendering-lists/npm-shrinkwrap.json', '5-4-react-rendering-lists/yarn.lock') == '' }}
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies (if any)
        run: |
          if [ -f 5-4-react-rendering-lists/package.json ]; then
            cd 5-4-react-rendering-lists
            (npm ci || npm install)
            cd ..
          fi

      # Set default due date (Riyadh time) or allow manual override via workflow_dispatch
      - name: Set Due Date env
        run: |
          if [ -n "${{ github.event.inputs.due_date }}" ]; then
            echo "DUE_DATE=${{ github.event.inputs.due_date }}" >> $GITHUB_ENV
          else
            echo "DUE_DATE=2025-10-08T23:59:59+03:00" >> $GITHUB_ENV
          fi

      - name: Run grader
        env:
          DUE_DATE: ${{ env.DUE_DATE }}
          SUBMITTED_AT: ${{ github.event.head_commit.timestamp }}
        run: |
          set -e
          GRADER_PATH="5-4-react-rendering-lists/scripts/grade.cjs"
          CONFIG_PATH="5-4-react-rendering-lists/grade.yml"

          if [ ! -f "$GRADER_PATH" ]; then
            echo "❌ Could not find grade.cjs at $GRADER_PATH" >&2
            exit 1
          fi

          if [ ! -f "$CONFIG_PATH" ]; then
            echo "❌ Could not find grade.yml at $CONFIG_PATH" >&2
            exit 1
          fi

          cd 5-4-react-rendering-lists

          if [ -n "$SUBMITTED_AT" ]; then
            node scripts/grade.cjs --root . --config grade.yml --submittedAt "$SUBMITTED_AT" | tee grade-console.txt
          else
            node scripts/grade.cjs --root . --config grade.yml | tee grade-console.txt
          fi

      - name: Upload grading artifacts
        uses: actions/upload-artifact@v4
        with:
          name: grade
          path: |
            5-4-react-rendering-lists/grade-report.md
            5-4-react-rendering-lists/grade-report.json
            5-4-react-rendering-lists/grade-console.txt

      - name: Post summary
        if: always()
        run: |
          if [ -f 5-4-react-rendering-lists/grade-report.md ]; then
            cat 5-4-react-rendering-lists/grade-report.md >> $GITHUB_STEP_SUMMARY
          else
            echo "No grade report produced." >> $GITHUB_STEP_SUMMARY
          fi
